# config.yaml
database_base: "/home/chandru/lu2025-12-38/Students/chandru/kraken_databases"
raw_data:  "/home/chandru/tel-megiddo/data/telmgd_qced/"
log_dir: "/home/chandru/tel-megiddo/logs"
threads: 16
read_length: 50        # aDNA average read length for Bracken. This must be set accroding to the dataset.
kmer_len: 27           # K-mer size breaks the read into k sizes and compares it against the kraken database
minimizer_len: 21      # Analyzes all the possible minmizers inside a k-mer len. 27-21+1 = 5 possible minimizers
minimizer_spaces: 5    # This is to simulate the after how many nucleotides there is a space. This is to ensure the reads

genomes:

# Chicken relatives
  gallus_latest_ref:
    accession: "GCF_016699485.2"
    label: "Gallus gallus latest ref"
    taxid: 9031
    method: datasets

  gallus_complete:
    accession: "GCA_024206055.2"      
    label: "Gallus gallus complete genome"
    taxid: 9031
    method: datasets

  coturnix:
    accession: "GCF_001577835.2"
    label: "Japanese quail"
    taxid: 93934
    method: datasets

  turkey:
    accession: "GCF_000146605.3"
    label: "Turkey"
    taxid: 9103
    method: datasets

  phasianus:
    accession: "GCF_004143745.1"
    label: "Common pheasant"
    taxid: 9054
    method: datasets
  
# Bacteria


# Fish


db_builds:

  run_gallus_standard:
    includes:
      - gallus_latest_ref
      - coturnix
      - turkey
      - phasianus


  run_gallus_complete:
    includes:
      - gallus_complete
      - coturnix
      - turkey
      - phasianus
